### ISSUE TITLE
pandas, matplotlib requirements

### ISSUE THREAD

**Issue by Codie-Petersen** [the-aerospace-corporation/brainblocks#1]
I was running some of the examples and the multivariate_abnormalities_detection.py has an import for pandas and matplotlib. These two are not in the requirements.txt. Obviously, it's trivial to just "pip install pandas matplotlib", so that is not really the issue. However, I have made a docker container project working for brainblocks right now but I have to explicitly call the pip install command for those two rather than letting the build handle it. I was just wondering if you could add pandas and matplotlib to the requirements.txt so that any dockerfile needn't worry about any changes in the github project.

Not a huge issue, but it would be easier to maintain docker projects. Thanks.

**Comment by ddigiorg** [comment]
I will add pandas and matplotlib to requirements.txt tonight when I get home.  Thanks for the suggestion.

**Comment by ddigiorg** [comment]
Complete
