### ISSUE TITLE
Using dpc.load() from a python script. 

### ISSUE THREAD

**Issue by rphilip-sonasoft** [the-aerospace-corporation/brainblocks#16]
Once the PatternClassifier is saved, it seems as though the load() function returns None. 
Is there something that I am missing?

**Comment by gaolaowai** [comment]
@rphilip-sonasoft , provide a snippet example. Then if we figure it out, we can create a pull request here.

**Comment by gaolaowai** [comment]
This resolves an issue where connections weren't really being saved and reloaded.

**Comment by jacobeverist** [comment]
Fixed in 7bd5d2b96847e790cfce30a5e7203c2c563c90d4

**Comment by gaolaowai** [comment]
whoop whoop!

@jacobeverist , hope you're keeping well. Cheers!
