### ISSUE TITLE
errors by running experiments

### ISSUE THREAD

**Issue by Thanh-Binh** [the-aerospace-corporation/brainblocks#5]
Hi,
I try to run your experiments, but it failed.
Could you please help me? Thanks
```
python3 experiments/BBClassifier/run_high_dimensional_classifier_experiments.py 
Data Set 0
Traceback (most recent call last):
  File "experiments/BBClassifier/run_high_dimensional_classifier_experiments.py", line 648, in <module>
    run_classifier_total_neurons_experiment(datasets)
  File "experiments/BBClassifier/run_high_dimensional_classifier_experiments.py", line 506, in run_classifier_total_neurons_experiment
    results_per_dataset = evaluate(datasets, classifier_configs)
  File "experiments/BBClassifier/run_high_dimensional_classifier_experiments.py", line 165, in evaluate
    clf = BBClassifier(**bb_config)
TypeError: __init__() got an unexpected keyword argument 'num_neurons'
```

**Comment by jacobeverist** [comment]
Thanks for the issue report.   I believe these scripts used an older naming convention and we haven't updated the argument names.

The arguments you referenced are trying to be passed to BBClassifier defined here: https://github.com/the-aerospace-corporation/brainblocks/blob/master/src/python/tools/bbclassifier.py

In the 'run_classifier_total_neurons_experiments', you can change 'num_neurons' to 'num_s'.

To see working code for the classifier ability, look at the example code here:   https://github.com/the-aerospace-corporation/brainblocks/blob/master/examples/python/applications/sklearn_style_classifier.py

We will update this experiment script to make sure it works in future updates.

**Comment by jacobeverist** [comment]
Also, you can change 'num_acts' to 'num_as' wherever you find it.

**Comment by jacobeverist** [comment]
Fixed with current update.  https://github.com/the-aerospace-corporation/brainblocks/commit/0af47338bba2b26342f34ff71238f8f8a861a0a0
