### ISSUE TITLE
Anomaly detection results

### ISSUE THREAD

**Issue by Thanh-Binh** [the-aerospace-corporation/brainblocks#9]
I have just tested the current version for multivariate anomaly detection by running
python3 examples/python/applications/multivariate_abnormality_detection.py
but I never got a good results as in README.
Anomaly score is also very high (see below).

Any idea?
Do you have any example for predicting multiple values? I mean instead of anomaly score, I'd like to get predicted values and to plot them.
Thanks

![multivariate_output](https://user-images.githubusercontent.com/6269904/99876861-12133880-2bfa-11eb-83cb-75d4d77d5469.png)

**Comment by jacobeverist** [comment]
Sorry for late response.   I will need to investigate this.   Thanks for the report.

**Comment by Thanh-Binh** [comment]
@jacobeverist thanks

**Comment by Thanh-Binh** [comment]
it works now by the current version
